#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use App\NameSorter;
use App\FileValidator;
use App\FileContentExtractor;
use App\Output\FileOutput;
use App\Output\PrintToConsole;

if ($argc < 2) {
    fwrite(STDERR, "Usage: name-sorter <filename>\n");
    exit(1);
}

try {
    $filePath = $argv[1];

    $fileValidator = new FileValidator();
    $fileValidator->validate($filePath);

    $fileContentExtractor = new FileContentExtractor();
    $fileContent = $fileContentExtractor->extract(($filePath));

    $sorter = new NameSorter();
    $sortedNames = $sorter->sort($fileContent);
    $sorter->output(new FileOutput($sortedNames, 'sorted-names-list.txt'));
    $sorter->output(new PrintToConsole($sortedNames));
} catch (\Exception $e) {
    fwrite(STDERR, "Error: " . $e->getMessage() . "\n");
    exit(1);
}
